apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar
  template:
    metadata:
      labels:
        app: calendar
    spec:
      containers:
      - name: calendar
        image: calendar-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
        # env:
        # - name: POSTGRES_USER
        #   value: "otus_user"
        # - name: POSTGRES_PASSWORD
        #   value: "otus_password"
        # - name: POSTGRES_DB
        #   value: "calendar"
        # - name: POSTGRES_HOST
        #   value: "postgres-service" # Имя сервиса PostgreSQL
        # - name: POSTGRES_PORT
        #   value: "5432"
        # readinessProbe:
        #   exec:
        #     command: ["sh", "-c", "nc -z postgres-service 5432"]
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        # livenessProbe:
        #   exec:
        #     command: ["sh", "-c", "nc -z postgres-service 5432"]
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
