apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-postgres-pv
  namespace: default
spec:
  capacity:
    storage: {{ .Values.postgres.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.postgres.path }}
