logger:
    level: "INFO"

storage:
    type: "psql"

    psql:
        host: "localhost"
        port: 5432
        user: "otus_user"
        password: "otus_password"
        dbname: "calendar"
        sslmode: "disable"
        migration_dir: "migrations"
        exec_migration: true

gRpcGateWay:
    host: "0.0.0.0"
    port: 50052

gRpcServer: 
    host: "localhost"
    port: 50051
