[logger]
level = "INFO"

[storage]
    type = "psql"

    [storage.psql]
    host = "localhost"
    port = 5434
    user = "otus_user"
    password = "otus_password"
    dbname = "calendar"
    sslmode = "disable"
    migration = "migrations"

[server]
    host = "localhost"
    port = 8080