[logger]
level = "INFO"

[storage]
    type = "psql"

    [storage.psql]
    host = "localhost"
    port = 5434
    user = "otus_user"
    password = "otus_password"
    dbname = "calendar"
    sslmode = "disable"
    migration_dir = "migrations"
    exec_migration = true

[HTTPserver]
    host = "localhost"
    port = 8080

[gRPCServer]
    host = "localhost"
    port = 50051